### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by TinyCub** [microsoftenator2022/AlternateHumanTraits#6]
Dear MicroSoftenator,

I would like to help translate this mod into chinese. Please advise how I should proceed.

Thanks,
Cub

**Comment by microsoftenator2022** [comment]
I'm currently working on making this possible. It will hopefully be ready sometime in the next week. I'll update here with instructions when it is.

**Comment by microsoftenator2022** [comment]
I've created a basic tool for this here: https://github.com/microsoftenator2022/MicroWrath/releases/tag/localization-1.0

You can either open a new issue and upload the files [here](https://docs.google.com/forms/d/e/1FAIpQLScZIB2r6GmfOJ0R9sdS0-caVExN1tFZfg6HUDwyPSPZoXp8Vw/viewform?usp=sf_link) or create a pull request adding them to the Localization directory in this repository

Feel free to reply here or ping me on the Owlcat Discord server (Microsoftenator) if you have any questions or issues
